### ISSUE TITLE
pg.18, 2.1.2.3 Metadata Content 오타 수정

### ISSUE THREAD

**Issue by obzva** [bjpublic/Front-end#4]
Metadata Content의 예시 중에서, <nonscript>가 <noscript>로 수정되어야 합니다.

**Comment by bjpublic** [comment]
안녕하십니까, 비제이퍼블릭입니다.

오탈자 제보해주셔서 감사합니다. 
다음 쇄에 반영하도록 하겠습니다.

감사합니다.
